include("colortypes.jl")
include("core.jl")
include("map.jl")
include("overlays.jl")
include("io.jl")
include("readnrrd.jl")
@linux_only include("readremote.jl")
@windows_only include("readremote.jl")
@osx_only include("readOSX.jl")
include("algorithms.jl")
include("edge.jl")
