site_name: Images.jl
site_description: An image processing library for Julia
site_author: Tim Holy
repo_url: https://github.com/timholy/Images.jl.git
repo_name: GitHub
use_directory_urls: true

theme: material
extra:
#  logo: 'images/logo.png'
  palette:
    primary: 'indigo'
    accent: 'light blue'
  font:
    text: 'Source Pro'
    code: 'Source Code Pro'

extra_css:
  - assets/Documenter.css

extra_javascript:
  - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML
  - assets/mathjaxhelper.js

markdown_extensions:
  - extra
  - tables
  - fenced_code
#  - codehilite  # doesn't work locally, yet
#  - mdx_math  # errors

docs_dir: build

pages:
- Home: index.md
- User Guide:
  - Aims: aims.md
  - Core Concepts: core.md
  - Overlays: overlays.md
- Function Reference: function_reference.md
#- About:
#  - Contributing: contributing.md
#  - License: LICENSE.md
#  - Release Notes: NEWS.md
